name: Playwright QA

on: [push]

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps
        run: |
          npm install
          npx playwright install --with-deps

      - name: 23f1002415@ds.study.iitm.ac.in run scraper
        run: |
          node sumTables.js
